<?php

use App\Services\AutoLangService;

/**
 * Translate a virtual room / book / slideshow name for display.
 *
 * Always returns the appropriate translation for the CURRENT locale.
 * For unknown/new room names, auto-registers the key in both id/auth.php
 * and en/auth.php (EN translation auto-generated by AutoLangService).
 *
 * Flow:
 *   ID locale → always return raw ID name (DB stores Indonesian)
 *   EN locale → look up EN lang key; if missing → auto-register + return EN
 *
 * @param string $name  Raw name from DB (Indonesian)
 */
if (!function_exists('transRoomName')) {
    function transRoomName(string $name): string
    {
        if (!$name) {
            return $name;
        }

        $locale = app()->getLocale();

        // In ID locale, always return the raw ID name (no translation needed)
        if ($locale === 'id') {
            return $name;
        }

        // EN locale: build case-insensitive maps of both lang files
        $authEn = require resource_path('lang/en/auth.php');
        $authId = require resource_path('lang/id/auth.php');
        $authEnLower = array_change_key_case($authEn, CASE_LOWER);
        $authIdLower = array_change_key_case($authId, CASE_LOWER);

        // ── Step 1: Direct key match (PRIORITY) ─────────────────────────────────
        // Compute the key from the input name, then look up in EN file directly.
        // This ensures "Menuju Ruangan Satu" → Menuju_Ruangan_Satu → "Go to Room One"
        // even when other keys have the same ID value (e.g. Menuju_Ruangan_tiga).
        $inputKey = preg_replace('/[^a-zA-Z0-9]+/', '_', trim($name));
        $inputKeyLower = strtolower($inputKey);
        if (isset($authEnLower[$inputKeyLower])) {
            return $authEnLower[$inputKeyLower];
        }

        // ── Step 2: ID value match fallback ──────────────────────────────────────
        // For legacy / already-registered keys where ID value === $name.
        $normName = preg_replace('/\s+/', '', $name);
        foreach ($authId as $key => $idVal) {
            $normIdVal = preg_replace('/\s+/', '', $idVal);
            if ($normIdVal === $normName) {
                $keyLower = strtolower($key);
                if (isset($authEnLower[$keyLower]) && $authEnLower[$keyLower] !== $idVal) {
                    return $authEnLower[$keyLower];
                }
            }
        }

        // ── Step 3: No existing key → auto-register in both lang files ─────────
        // AutoLangService generates EN translation, creates both lang keys
        return AutoLangService::ensureKey($inputKey, $name);
    }
}
